export const ADD_POINT_PROFIL = 'ADD_POINT_PROFIL'
export const REMOVE_POINT_PROFIL = 'REMOVE_POINT_PROFIL'
export const ADD_RESPONSE_COUNT  = 'ADD_RESPONSE_COUNT'
export const REMOVE_ONE_RESPONSE = 'REMOVE_ONE_RESPONSE'

export const SET_LAST_ANSWER = 'SET_LAST_ANSWER'
export const REMOVE_LAST_ANSWER = 'REMOVE_LAST_ANSWER'

export const ADD_RESPONSE_GESTION_COUNT = 'ADD_RESPONSE_GESTION_COUNT'
export const REMOVE_ONE_RESPONSE_GESTION = 'REMOVE_ONE_RESPONSE_GESTION'
export const ADD_POINT_GESTION = 'ADD_POINT_GESTION'
export const REMOVE_POINT_GESTION = 'REMOVE_POINT_GESTION'


export const SET_PROPOSITION_SELECTED  = 'SET_PROPOSITION_SELECTED'


export const SET_IS_MINOR = "SET_IS_MINOR"
export const SET_PROFIL_PRUDENT_AUTO = "SET_PROFIL_PRUDENT_AUTO"
export const SET_PROFIL_TRADER_AUTO = "SET_PROFIL_TRADER_AUTO"