export const ADD_POINT_PROFIL = 'ADD_POINT_PROFIL'
export const ADD_POINT_GESTION = 'ADD_POINT_GESTION'

export const ADD_RESPONSE_GESTION_COUNT = 'ADD_RESPONSE_GESTION_COUNT'
export const ADD_RESPONSE_COUNT  = 'ADD_RESPONSE_COUNT'

export const SET_PROPOSITION_SELECTED  = 'SET_PROPOSITION_SELECTED'
